spring.application.name=ordermymeal
spring.datasource.url=jdbc:postgresql://localhost:5432/ordermymeal

spring.datasource.username=postgres
spring.datasource.password=sk1234

server.port=8083

# Enable actuator mappings endpoint
management.endpoints.web.exposure.include=health,info,mappings
# ===============================
# OrderMyMeal Auth
# ===============================

ordermymeal.auth.otp-expiry=5m

ordermymeal.auth.max-otp-attempts=5

ordermymeal.auth.session-lifetime=30d

ordermymeal.auth.resend-window=10m

ordermymeal.auth.max-otp-requests-per-email=5

ordermymeal.auth.max-otp-requests-per-ip=20

# Development only
ordermymeal.auth.dev-otp-logging=true
ordermymeal.auth.dev-otp-only=true

# Change these values before production
ordermymeal.auth.otp-hash-secret=${OMM_OTP_HASH_SECRET:change-this-development-otp-secret}

ordermymeal.auth.session-hash-secret=${OMM_SESSION_HASH_SECRET:change-this-development-session-secret}


# ===============================
# JPA / Hibernate
# ===============================

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=false

spring.jpa.properties.hibernate.format_sql=false


# ===============================
# Flyway
# ===============================

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.out-of-order=true

# ===============================
# Email / SMTP
# ===============================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

